# Production values. Use them with: -f notes-chart/values-prod.yaml
replicaCount: 3

image:
  repository: nginx
  tag: "1.25"

service:
  port: 80
  nodePort: 30315

app:
  name: notes-app
  environment: production
  notes:
    - "Write the Helm chart"
    - "Test the chart in development"
    - "Promote the chart to production with values-prod.yaml"
