# The Service selects all Pods with app=app-recreate.
apiVersion: v1
kind: Service
metadata:
  name: app-recreate-service
  namespace: s10-recreate
  labels:
    app: app-recreate
spec:
  type: ClusterIP
  selector:
    app: app-recreate
  ports:
    - name: http
      port: 80
      targetPort: 80
