apiVersion: v1
kind: Namespace
metadata:
  name: s17-devsecops
  labels:
    # Pod Security Admission: reject Pods that do not meet the "restricted" profile.
    pod-security.kubernetes.io/enforce: restricted
