# A small Deployment with 2 replicas. Use it with "kubectl get -o wide" and "kubectl top".
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: s14-commands
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
